repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort # sort imports
      args: [--sl, --profile=black]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black # code formatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-docstring-first
  - repo: https://github.com/PyCQA/flake8/
    rev: 4.0.1
    hooks:
      - id: flake8 # coding style (PEP8) and programming errors
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit # security issues
        args: [-c, .bandit]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7e1ceac2d5967f5428f0b1900cb7fe26da724bb1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, chore, ci, build] # optional: list of Conventional Commits types to allow
